apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: todoapp
type: Opaque
data:
  SECRET_KEY: QGUyKHl4KXYmdGdoM19zPTB5amEtaSFkcGVieHN6XmRnNDd4KS1rJmtxXzN6Zio5ZSoK
  DB_USER: bXlzcWx1c2Vy
  DB_PASSWORD: VmVyeUhhcmRQYXNzV2Q=
  DB_HOST: bXlzcWwtMC5teXNxbC5teXNxbC5zdmMuY2x1c3Rlci5sb2NhbAo=

---

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: VmVyeUhhcmRQYXNzV2RSb290
  MYSQL_USER: bXlzcWx1c2Vy
  MYSQL_PASSWORD: VmVyeUhhcmRQYXNzV2Q=
